
import React from 'react';
import { ShieldCheck, Truck, RefreshCw, FileText, ChevronRight } from 'lucide-react';

const PolicyPage = () => {
  const policies = [
    { id: 'privacy', title: 'Privacy Policy', icon: <ShieldCheck size={16} /> },
    { id: 'shipping', title: 'Shipping Policy', icon: <Truck size={16} /> },
    { id: 'returns', title: 'Returns & Refunds', icon: <RefreshCw size={16} /> },
    { id: 'terms', title: 'Terms of Service', icon: <FileText size={16} /> },
  ];

  return (
    <div className="bg-white min-h-screen font-sans text-black">
      {/* 1. MINIMAL HEADER */}
      <header className="px-8 py-10 border-b border-black flex flex-col items-end">
        <h1 className="text-2xl font-bold tracking-tighter uppercase">Legal Center</h1>
        <p className="text-[9px] uppercase tracking-[0.3em] text-gray-400 mt-1">Vastra Culture Ecosystem</p>
      </header>

      <div className="max-w-7xl mx-auto flex flex-col md:flex-row">
        
        {/* 2. SIDEBAR NAVIGATION (No extra margin) */}
        <aside className="w-full md:w-64 border-b md:border-b-0 md:border-r border-black p-0">
          <nav className="flex flex-col">
            {policies.map((policy) => (
              <button 
                key={policy.id}
                className="flex items-center justify-between px-8 py-6 border-b border-black/5 hover:bg-black hover:text-white transition-all group"
              >
                <div className="flex items-center gap-4">
                  {policy.icon}
                  <span className="text-[10px] font-bold uppercase tracking-widest">{policy.title}</span>
                </div>
                <ChevronRight size={14} className="opacity-0 group-hover:opacity-100 transition-opacity" />
              </button>
            ))}
          </nav>
        </aside>

        {/* 3. CONTENT AREA */}
        <main className="flex-1 p-8 md:p-12 lg:p-16">
          <section className="max-w-3xl">
            <h2 className="text-xl font-bold uppercase tracking-tight mb-8">Shipping & Delivery Policy</h2>
            
            <div className="space-y-10 text-sm leading-relaxed text-gray-600">
              {/* Block 1 */}
              <div className="space-y-2">
                <h4 className="text-[10px] font-bold uppercase tracking-widest text-black">01. Order Processing</h4>
                <p>
                  As a dropshipping platform, Vastra Culture routes orders directly to verified suppliers. 
                  Orders are typically processed and handed over to logistics partners within 24 to 48 hours.
                </p>
              </div>

              {/* Block 2 */}
              <div className="space-y-2">
                <h4 className="text-[10px] font-bold uppercase tracking-widest text-black">02. Logistics & Tracking</h4>
                <p>
                  Our primary delivery network covers 15,000+ pin codes across India. Once the supplier 
                  generates the manifest, a real-time tracking link is shared via WhatsApp and Email.
                </p>
              </div>

              {/* Block 3: Special Feature Callout */}
              <div className="border border-black p-6 bg-gray-50">
                <h4 className="text-[10px] font-bold uppercase tracking-widest text-black mb-3">Address Modification</h4>
                <p className="text-xs">
                  Unique to our platform, you may modify your delivery address within 2 hours of order 
                  placement, provided the shipping label has not been generated by the supplier.
                </p>
              </div>

              {/* Block 4 */}
              <div className="space-y-2">
                <h4 className="text-[10px] font-bold uppercase tracking-widest text-black">03. Estimated Timelines</h4>
                <div className="border-t border-black/10 pt-4 grid grid-cols-2 gap-4">
                  <div>
                    <span className="block text-[9px] font-bold text-gray-400 uppercase">Metro Cities</span>
                    <span className="font-bold">3 - 5 Days</span>
                  </div>
                  <div>
                    <span className="block text-[9px] font-bold text-gray-400 uppercase">Tier 2/3 Cities</span>
                    <span className="font-bold">5 - 8 Days</span>
                  </div>
                </div>
              </div>
            </div>

            {/* Support CTA */}
            <div className="mt-20 pt-10 border-t border-black">
              <p className="text-[10px] font-bold uppercase tracking-widest text-gray-400 mb-4">Questions regarding policy?</p>
              <div className="flex gap-6">
                <a href="#" className="text-[10px] font-bold uppercase tracking-widest underline underline-offset-4">Email Legal</a>
                <a href="#" className="text-[10px] font-bold uppercase tracking-widest underline underline-offset-4">WhatsApp Support</a>
              </div>
            </div>
          </section>
        </main>

      </div>
    </div>
  );
};

export default PolicyPage;